### ISSUE TITLE
Update ontology redirects for CSL 1.0.2

### ISSUE THREAD

**Issue by larsgw** [citation-style-language/citation-style-language.github.io#49]
https://github.com/citation-style-language/citation-style-language.github.io/blob/master/_pages/ontology.md

**Comment by bwiernik** [comment]
@bdarcus can you make me an admin of this repo?

**Comment by bdarcus** [comment]
Done.

**Comment by bwiernik** [comment]
@larsgw All the redirects seem to go to the right sections for me. What problems are you seeing?

**Comment by larsgw** [comment]
I mean that the new types and roles are still missing. I can make a pull request if you want.

**Comment by bwiernik** [comment]
Sure I'm not sure what exactly you mean, so a pull request would be great
